### ISSUE TITLE
No such table: sqlite3_foreign_keys

### ISSUE THREAD

**Issue by notinlist** [mlomnicki/automatic_foreign_key#4]
Hello,

  Source and trace.

Thanks, Nil.

```
class CreateTests < ActiveRecord::Migration
  def self.up
    create_table :things, :id => false do |t|
      t.integer :id, :limit => 8
      t.string :name, :limit => 32
      t.primary_key :id
    end
    add_index :things, :name

    create_table :stuffs do |t|
      t.string :name, :limit => 32
    end
    add_index :stuffs, :name
  end

  def self.down
    drop_table :things
    drop_table :stuffs
  end
end
```

And the trace...

```
rake aborted!
An error has occurred, this and all later migrations canceled:

ActiveRecord::JDBCError: no such table: sqlite3_foreign_keys:         SELECT *
          FROM sqlite3_foreign_keys
         WHERE "to_table_name" = 'things'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract_adapter.rb:207:in `log'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/activerecord-jdbc-adapter-1.1.1/lib/arjdbc/jdbc/adapter.rb:183:in `execute'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/activerecord-jdbc-adapter-1.1.1/lib/arjdbc/sqlite3/adapter.rb:198:in `select'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in `select_all'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/query_cache.rb:56:in `select_all'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/redhillonrails_core-1.1.3/lib/redhillonrails_core/active_record/connection_adapters/sqlite3_adapter.rb:95:in `load_foreign_keys'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/redhillonrails_core-1.1.3/lib/redhillonrails_core/active_record/connection_adapters/sqlite3_adapter.rb:59:in `reverse_foreign_keys'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/redhillonrails_core-1.1.3/lib/redhillonrails_core/active_record/connection_adapters/abstract_adapter.rb:64:in `drop_table_with_redhillonrails_core'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/activerecord-3.0.7/lib/active_record/migration.rb:383:in `method_missing'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/activerecord-3.0.7/lib/active_record/migration.rb:359:in `say_with_time'
C:/opt/jruby-ovo-1.5.1/lib/ruby/1.8/benchmark.rb:293:in `measure'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/activerecord-3.0.7/lib/active_record/migration.rb:359:in `say_with_time'
C:/opt/jruby-ovo-1.5.1/lib/ruby/gems/1.8/gems/activerecord-3.0.7/lib/active_record/migration.rb:379:in `method_missing'
D:/projects/tmp/OVOMiner/db/migrate/20000101000000_create_tests.rb:17:in `down'
```

**Comment by donv** [comment]
I am getting this now.  Any thoughts on what is the cause?

**Comment by mlomnicki** [comment]
Have you tried to switch to [schema_plus](https://github.com/lomba/schema_plus) ? automatic_foreign_key isn't maintained anymore

**Comment by donv** [comment]
I have switched on one project, but hoped I could defer it a bit.

**Comment by donv** [comment]
Switching to schema_plus now :)  Thanks!

You should close this issue since it is over a year old, and the gem is unsupported.

**Comment by notinlist** [comment]
Thanks for the hint.
